global using IntegratedProtection.Application;
global using IntegratedProtection.Application.CentralSecurity.Features.Criminals.Commands;
global using IntegratedProtection.Application.CentralSecurity.Features.Criminals.Queries;
global using IntegratedProtection.Application.CentralSecurity.ViewModels;
global using IntegratedProtection.Application.CivilRegistry.Features.Cards.Commands;
global using IntegratedProtection.Application.CivilRegistry.Features.Cards.Queries;
global using IntegratedProtection.Application.CivilRegistry.ViewModels;
global using IntegratedProtection.Application.Traffic.Features.Cars.Commands;
global using IntegratedProtection.Application.Traffic.Features.Cars.Queries;
global using IntegratedProtection.Application.Traffic.Features.StolenCars.Commands;
global using IntegratedProtection.Application.Traffic.Features.StolenCars.Queries;
global using IntegratedProtection.Application.Traffic.Features.TrafficOfficers.Commands;
global using IntegratedProtection.Application.Traffic.Features.TrafficOfficers.Queries;
global using IntegratedProtection.Application.Traffic.ViewModels;
global using IntegratedProtection.Infrastructure;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using System.Text.Json.Serialization;
namespace IntegratedProtection.API;

